### ISSUE TITLE
Avoid absolute path in xbot2 params

### ISSUE THREAD

**Issue by lia2790** [ADVRHumanoids/XBotControl#51]
Hi all,

I am trying to avoid absolute path in xbot control plugin passed as a parameter as mentioned [here](https://github.com/ADVRHumanoids/VariableImpedanceRegulation/issues/23#issue-1046529835).

Basically, I want to change the code below

```yaml
joint_impedance_control: 
        thread: rt_main
        type: joint_impedance_controlH
        params:
            urdf_path: {value: /home/liana/catkin_ws/src/VariableImpedanceRegulation/robots/6dof/urdf/6dof.urdf, type: string}
            srdf_path: {value: /home/liana/catkin_ws/src/VariableImpedanceRegulation/robots/6dof/srdf/6dof.srdf, type: string}
            task_path: {value: /home/liana/catkin_ws/src/VariableImpedanceRegulation/robots/6dof/task/6dof_stack.yaml, type: string}
``` 

into the following

```yaml
joint_impedance_control: 
        thread: rt_main
        type: joint_impedance_controlH
        params:
            urdf_path: {value: $(rospack find vir_singlejoint)/robots/6dof/urdf/6dof.urdf, type: string}
            srdf_path: {value: $(rospack find vir_singlejoint)/robots/6dof/srdf/6dof.srdf, type: string}
            task_path: {value: $(rospack find vir_singlejoint)/robots/6dof/task/6dof_stack.yaml, type: string}
``` 

in such a way to have a more portable code.

I tried this but I obtain an error as below
```
liana@iitadvrlw003 ~/catkin_ws/src/VariableImpedanceRegulation/configs/xbot (cartesIO)$ ./setup_xbot2_gz_6dof.sh 
/home/liana/catkin_ws/src/VariableImpedanceRegulation/configs/xbot/robot/6dof.yaml
[warn][jm] running with disabled safety policies 
[ok  ][xbot2-core] started running 
Initializing CartesIO Interface...
uploading models urdf srdf...
[err ] in generate_jidmap: urdf does not exists! 
generating jidmap...
setting model type...
[ERROR] [1636368178.756491295]: Error document empty.
``` 
![Screenshot from 2021-11-08 15-36-18](https://user-images.githubusercontent.com/15608027/140770308-caaa15e2-45c1-4dac-ad1d-5654d44fb23d.png)

**To replicate the error**

1. clone the repo [here](https://github.com/ADVRHumanoids/VariableImpedanceRegulation)
2. go to the cartesIO_debug branch
3. go to the commit ISSUE_ABSOLUTE_PATH 30bdc4dc476adb6b4a32db7ac8d8fa9e0fc1dfa8
3. run `roslaunch vir_singlejoint vir_6dof_gazebo.launch` in a terminal
4. run  `./setup_xbot2_gz_6dof.sh` in other terminal
5. then you should see the error reported.
(source the terminals)
